### ISSUE TITLE
Text input does not work

### ISSUE THREAD

**Issue by Turbovadim** [Qawaz/compose-code-editor#10]
When using a virtual keyboard, text input does not work. Although when using a physical one in the emulator, everything is fine.

**Comment by wakaztahir** [comment]
Jetpack compose has updated text field a lot , I am still waiting for this issue to be fixed 

https://issuetracker.google.com/issues/192043120

Now after taking input launch a new scope and parse the code in that scope , lazily , set the new annotated string or text field value after the scope is done , maybe have a delay & keep cancelling the editing job when the user is typing.

I'll let you know when I have a better solution.

**Comment by wakaztahir** [comment]
```kotlin
      var codeJob by remember { mutableStateOf<Job?>(null) }

        OutlinedTextField(
            modifier = Modifier.fillMaxWidth(),
            value = textFieldValue,
            onValueChange = {
                textFieldValue = it.copy(
//                    annotatedString = parseCodeAsAnnotatedString(
//                        parser = parser,
//                        theme = theme,
//                        lang = block.lang,
//                        code = it.text
//                    )
                )

                codeJob?.cancel()
                codeJob = scope.launch {
                    delay(800)
                    textFieldValue = textFieldValue.copy(
                        annotatedString = parseCodeAsAnnotatedString(
                            parser = parser,
                            theme = theme,
                            lang = block.lang,
                            code = textFieldValue.text
                        )
                    )
                }
)
```

**Comment by wakaztahir** [comment]
working on it

**Comment by Turbovadim** [comment]
I'm waiting. I hope that everything will work out

**Comment by wakaztahir** [comment]
https://issuetracker.google.com/issues/265579399

I had to make an issue , waiting for their response.

**Comment by estivensh4** [comment]
I also have the same problem, it has not been solved yet?

**Comment by wakaztahir** [comment]
no
