### ISSUE TITLE
Allow extending Lang

### ISSUE THREAD

**Issue by frmz** [Qawaz/compose-code-editor#11]
Currently shortcutStylePatterns / fallthroughStylePatterns is internal, this doesnt allow extending with our own language without adding it here, is it intentional?

**Comment by wakaztahir** [comment]
Hi , It would be available in the next version !

**Comment by wakaztahir** [comment]
https://github.com/Qawaz/compose-code-editor/blob/e39e55502258dc2f76b891b3ee1fbf5096f62de2/demo/common/src/commonMain/kotlin/com/wakaztahir/common/DisplayCodeEditor.kt#L122
