### ISSUE TITLE
Provide Kotlin Language for Android library version

### ISSUE THREAD

**Issue by AdrianDev0** [Qawaz/compose-code-editor#15]
Hi, could you add the language `Kotlin` (CodeLang.Kotlin) to the android version (2.0.3) of the repo ?

Kind regards :)

**Comment by wakaztahir** [comment]
You could upgrade to the multiplatform library for compose , which is using latest version of kotlin and I've fixed many bugs in that library , only android variant of the multiplatform library will be used in your project when using that library

https://github.com/orgs/Qawaz/packages?repo_name=compose-code-editor

The old repo android version 2.0.3 , is very old with java code and If I update it , it requires that I publish the library with that version on Jitpack , which is a lot of work for one Kotlin file , I would suggest you to setup github packages , download the multiplatform library or android variant , and let me know if you encounter any problems / bugs , I'll help you fix them.
