### ISSUE TITLE
Language support for Rust

### ISSUE THREAD

**Issue by mainrs** [Qawaz/compose-code-editor#9]
https://www.rust-lang.org/

**Comment by wakaztahir** [comment]
PR's are welcome.

**Comment by wakaztahir** [comment]
By the way You can use Rust Extensions = "rc", "rs", "rust"
Try passing the extension to `parseCodeAsAnnotatedString` defined here https://github.com/Qawaz/compose-code-editor/blob/main/codeeditor/src/commonMain/kotlin/com/wakaztahir/codeeditor/utils/Annotation.kt#L17
